version: '3.7'

networks:
  proxy:
    external: true

services:

### MariaDB Container #######################################

    mariadb:
      build:
        context: ./mariadb
        args:
          MARIADB_IMAGE: ${MARIADB_IMAGE}
      volumes:
        - mariadb:/var/lib/mysql
        - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MARIADB_PORT}:3306"
      networks:
        - proxy
      environment:
        - MYSQL_DATABASE=${MARIADB_DATABASE}
        - MYSQL_USER=${MARIADB_USER}
        - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      restart: unless-stopped

### phpMyAdmin Container ####################################

    phpmyadmin:
      build:
        context: ./phpmyadmin
        args:
          PMA_IMAGE: ${PMA_IMAGE}
      environment:
        - PMA_ARBITRARY=1
      ports:
        - "${PMA_PORT}:80"
      networks:
        - proxy
      depends_on:
        - "mariadb"
      restart: unless-stopped

### Shinobi Container #######################################

    shinobi:
      image: ${SHINOBI_IMAGE}
      depends_on:
        - "mariadb"
      ports:
        - "8080:8080"
      environment:
        - DATABASE_HOST=mariadb
        - DATABASE_USER=${SHINOBI_DB_USER}
        - DATABASE_PASSWORD=${SHINOBI_DB_PASSWORD}
        - DATABASE_PORT=${SHINOBI_DB_PORT}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.shinobi.rule=Host(`cctv.change.me`)"
        - "traefik.http.routers.shinobi.entrypoints=http"
        - "traefik.http.services.shinobi.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.shinobi.middlewares=https-redirect"
        - "traefik.http.routers.shinobi-secure.entrypoints=https"
        - "traefik.http.routers.shinobi-secure.rule=Host(`cctv.change.me`)"
        - "traefik.http.routers.shinobi-secure.tls=true"
        - "traefik.http.routers.shinobi-secure.tls.certresolver=http"
      networks:
        - proxy
      volumes:
        - ${DATA_SAVE_PATH}/shinobi/config:/config
        - ${DATA_SAVE_PATH}/shinobi/videos:/opt/shinobi/videos
        - ${DATA_SAVE_PATH}/shinobi/datadir:/var/lib/mysql
      restart: unless-stopped

### Volumes Setup #############################################

volumes:
  mariadb:

